TARGET_mailbox := libmailbox.a
SRCS_mailbox := mailbox.c xmailbox.c pagesize.c
OBJS_mailbox := $(SRCS_mailbox:%.c=%.c.o)
DEPS_mailbox := $(SRCS_mailbox:%.c=%.c.d)
ALLDEPS_mailbox = $(MAKEFILE_LIST_SANS_DEPS)
CFLAGS_mailbox := -Wall -Wextra -O2
